version: '3.9'
services:
  db:
    container_name: imersao-fc6-php-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'

  redis:
    container_name: imersao-fc6-php-redis
    image: redis:6.2
    ports:
      - '6379:6379'

networks:
  default:
    name: imersao-fc6-php